name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: rojo-rbx/setup-foreman@6d3c8043db88319f8482262680b37f73595a8686
      name: Install Foreman
      
      with:
          token: ${{ SECRETS.GITHUB_TOKEN }}

    - name: Lint
      run: |
        selene ./src

  style:
    name: Styling
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: JohnnyMorganz/stylua-action@v4
      with:
        token: ${{ SECRETS.GITHUB_TOKEN }}
        version: 0.20.0
        args: --check .